### ISSUE TITLE
ValueError: Missing required table fvar

### ISSUE THREAD

**Issue by JonathanAlumbaugh** [jonpalmisc/vfit#13]
Sorry to bring this up if the project is defunct (or I'm missing some obvious step), I keep getting this error trying to generate a set of static font family files:

```
$ vfit -o ./output-folder -f woff2 sample.json font.otf
Traceback (most recent call last):                                                                            
  File "/home/jonathan/.local/bin/vfit", line 8, in <module>
    sys.exit(main())
  File "/home/jonathan/.local/lib/python3.9/site-packages/vfit/app.py", line 65, in main
    core.generateInstances(cfg, args)
  File "/home/jonathan/.local/lib/python3.9/site-packages/vfit/core.py", line 21, in generateInstances
    instantiateFont(font, style["axes"], inplace=True, overlap=True)
  File "/home/jonathan/.local/lib/python3.9/site-packages/fontTools/varLib/instancer/__init__.py", line 1196, in instantiateVariableFont
    sanityCheckVariableTables(varfont)
  File "/home/jonathan/.local/lib/python3.9/site-packages/fontTools/varLib/instancer/__init__.py", line 1126, in sanityCheckVariableTables
    raise ValueError("Missing required table fvar")
ValueError: Missing required table fvar
```

**Comment by JonathanAlumbaugh** [comment]
My apologies, I'm not familiar with font files and it looks like this an issue with the font file.
